/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

/**
 *
 * @author sajithjeewantha
 */
public class EmailTemplate {

    private String template1 = "<!DOCTYPE html>\n"
            + "<html lang=\"en\">\n"
            + "\n"
            + "<head>\n"
            + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
            + "    <title>Simple Transactional Email</title>\n"
            + "    <style media=\"all\" type=\"text/css\">\n"
            + "        @media all {\n"
            + "            .btn-primary table td:hover {\n"
            + "                background-color: #ec0867 !important;\n"
            + "            }\n"
            + "\n"
            + "            .btn-primary a:hover {\n"
            + "                background-color: #ec0867 !important;\n"
            + "                border-color: #ec0867 !important;\n"
            + "            }\n"
            + "        }\n"
            + "\n"
            + "        @media only screen and (max-width: 640px) {\n"
            + "\n"
            + "            .main p,\n"
            + "            .main td,\n"
            + "            .main span {\n"
            + "                font-size: 16px !important;\n"
            + "            }\n"
            + "\n"
            + "            .wrapper {\n"
            + "                padding: 8px !important;\n"
            + "            }\n"
            + "\n"
            + "            .content {\n"
            + "                padding: 0 !important;\n"
            + "            }\n"
            + "\n"
            + "            .container {\n"
            + "                padding: 0 !important;\n"
            + "                padding-top: 8px !important;\n"
            + "                width: 100% !important;\n"
            + "            }\n"
            + "\n"
            + "            .main {\n"
            + "                border-left-width: 0 !important;\n"
            + "                border-radius: 0 !important;\n"
            + "                border-right-width: 0 !important;\n"
            + "            }\n"
            + "\n"
            + "            .btn table {\n"
            + "                max-width: 100% !important;\n"
            + "                width: 100% !important;\n"
            + "            }\n"
            + "\n"
            + "            .btn a {\n"
            + "                font-size: 16px !important;\n"
            + "                max-width: 100% !important;\n"
            + "                width: 100% !important;\n"
            + "            }\n"
            + "        }\n"
            + "\n"
            + "        @media all {\n"
            + "            .ExternalClass {\n"
            + "                width: 100%;\n"
            + "            }\n"
            + "\n"
            + "            .ExternalClass,\n"
            + "            .ExternalClass p,\n"
            + "            .ExternalClass span,\n"
            + "            .ExternalClass font,\n"
            + "            .ExternalClass td,\n"
            + "            .ExternalClass div {\n"
            + "                line-height: 100%;\n"
            + "            }\n"
            + "\n"
            + "            .apple-link a {\n"
            + "                color: inherit !important;\n"
            + "                font-family: inherit !important;\n"
            + "                font-size: inherit !important;\n"
            + "                font-weight: inherit !important;\n"
            + "                line-height: inherit !important;\n"
            + "                text-decoration: none !important;\n"
            + "            }\n"
            + "\n"
            + "            #MessageViewBody a {\n"
            + "                color: inherit;\n"
            + "                text-decoration: none;\n"
            + "                font-size: inherit;\n"
            + "                font-family: inherit;\n"
            + "                font-weight: inherit;\n"
            + "                line-height: inherit;\n"
            + "            }\n"
            + "        }\n"
            + "    </style>\n"
            + "</head>\n"
            + "\n"
            + "<body style=\"\n"
            + "      font-family: Helvetica, sans-serif;\n"
            + "      -webkit-font-smoothing: antialiased;\n"
            + "      font-size: 16px;\n"
            + "      line-height: 1.3;\n"
            + "      -ms-text-size-adjust: 100%;\n"
            + "      -webkit-text-size-adjust: 100%;\n"
            + "      background-color: #f4f5f6;\n"
            + "      margin: 0;\n"
            + "      padding: 0;\n"
            + "    \">\n"
            + "    <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\" style=\"\n"
            + "        border-collapse: separate;\n"
            + "        mso-table-lspace: 0pt;\n"
            + "        mso-table-rspace: 0pt;\n"
            + "        background-color: #f4f5f6;\n"
            + "        width: 100%;\n"
            + "      \" width=\"100%\" bgcolor=\"#f4f5f6\">\n"
            + "        <tr>\n"
            + "            <td style=\"\n"
            + "            font-family: Helvetica, sans-serif;\n"
            + "            font-size: 16px;\n"
            + "            vertical-align: top;\n"
            + "          \" valign=\"top\">\n"
            + "                &nbsp;\n"
            + "            </td>\n"
            + "            <td class=\"container\" style=\"\n"
            + "            font-family: Helvetica, sans-serif;\n"
            + "            font-size: 16px;\n"
            + "            vertical-align: top;\n"
            + "            max-width: 600px;\n"
            + "            padding: 0;\n"
            + "            padding-top: 24px;\n"
            + "            width: 600px;\n"
            + "            margin: 0 auto;\n"
            + "          \" width=\"600\" valign=\"top\">\n"
            + "                <div class=\"content\" style=\"\n"
            + "              box-sizing: border-box;\n"
            + "              display: block;\n"
            + "              margin: 0 auto;\n"
            + "              max-width: 600px;\n"
            + "              padding: 0;\n"
            + "            \">\n"
            + "                    <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"main\" style=\"\n"
            + "                border-collapse: separate;\n"
            + "                mso-table-lspace: 0pt;\n"
            + "                mso-table-rspace: 0pt;\n"
            + "                background: #ffffff;\n"
            + "                border: 1px solid #eaebed;\n"
            + "                border-radius: 16px;\n"
            + "                width: 100%;\n"
            + "              \" width=\"100%\">\n"
            + "                        <!-- START MAIN CONTENT AREA -->\n"
            + "                        <tr>\n"
            + "                            <td class=\"wrapper\" style=\"\n"
            + "                    font-family: Helvetica, sans-serif;\n"
            + "                    font-size: 16px;\n"
            + "                    vertical-align: top;\n"
            + "                    box-sizing: border-box;\n"
            + "                    padding: 24px;\n"
            + "                  \" valign=\"top\">\n"
            + "                                <p style=\"\n"
            + "                      font-family: Helvetica, sans-serif;\n"
            + "                      font-size: 16px;\n"
            + "                      font-weight: normal;\n"
            + "                      margin: 0;\n"
            + "                      margin-bottom: 16px;\n"
            + "                    \">\n"
            + "                                    Hi there\n"
            + "                                </p>\n"
            + "                                <p style=\"\n"
            + "                      font-family: Helvetica, sans-serif;\n"
            + "                      font-size: 16px;\n"
            + "                      font-weight: normal;\n"
            + "                      margin: 0;\n"
            + "                      margin-bottom: 16px;\n"
            + "                    \">\n"
            + "                                    Sometimes you just want to send a simple HTML email with a\n"
            + "                                    simple design and clear call to action. This is it.\n"
            + "                                </p>\n"
            + "                                \n"
            + "                                <h1>";

    private String template2 = "</h1>\n"
            + "                                <p style=\"\n"
            + "                      font-family: Helvetica, sans-serif;\n"
            + "                      font-size: 16px;\n"
            + "                      font-weight: normal;\n"
            + "                      margin: 0;\n"
            + "                      margin-bottom: 16px;\n"
            + "                    \">\n"
            + "                                    This is a really simple email template. It's sole purpose is\n"
            + "                                    to get the recipient to click the button with no\n"
            + "                                    distractions.\n"
            + "                                </p>\n"
            + "                                <p style=\"\n"
            + "                      font-family: Helvetica, sans-serif;\n"
            + "                      font-size: 16px;\n"
            + "                      font-weight: normal;\n"
            + "                      margin: 0;\n"
            + "                      margin-bottom: 16px;\n"
            + "                    \">\n"
            + "                                    Good luck! Hope it works.\n"
            + "                                </p>\n"
            + "                            </td>\n"
            + "                        </tr>\n"
            + "\n"
            + "                        <!-- END MAIN CONTENT AREA -->\n"
            + "                    </table>\n"
            + "\n"
            + "\n"
            + "                    <!-- END CENTERED WHITE CONTAINER -->\n"
            + "                </div>\n"
            + "            </td>\n"
            + "            <td style=\"\n"
            + "            font-family: Helvetica, sans-serif;\n"
            + "            font-size: 16px;\n"
            + "            vertical-align: top;\n"
            + "          \" valign=\"top\">\n"
            + "                &nbsp;\n"
            + "            </td>\n"
            + "        </tr>\n"
            + "    </table>\n"
            + "</body>\n"
            + "\n"
            + "</html>";

    /**
     * @return the template1
     */
    public String getTemplate1() {
        return template1;
    }

    /**
     * @return the template2
     */
    public String getTemplate2() {
        return template2;
    }

}
